import { DigimonSeeds } from "@core/enums/digimon-seeds.enum";

export const LOCATIONS = [
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_LOGIN_MOUNTAIN',
    img: 'assets/environments/loginmountain.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.BOTAMON, levelRange: { min: 1, max: 5 } },
      { seed: DigimonSeeds.KOROMON, levelRange: { min: 1, max: 6 } },
      { seed: DigimonSeeds.PITCHMON, levelRange: { min: 1, max: 5 } },
      { seed: DigimonSeeds.PUTTIMON, levelRange: { min: 1, max: 5 } },
      { seed: DigimonSeeds.MINOMON, levelRange: { min: 1, max: 6 } },
      { seed: DigimonSeeds.AGUMON, levelRange: { min: 5, max: 8 } },
      { seed: DigimonSeeds.GREYMON, levelRange: { min: 6, max: 10 } },
      { seed: DigimonSeeds.FALCOMON, levelRange: { min: 4, max: 8 } },
      { seed: DigimonSeeds.GOBURIMON, levelRange: { min: 4, max: 8 } },
      { seed: DigimonSeeds.TSUMEMON, levelRange: { min: 2, max: 6 } },
      { seed: DigimonSeeds.TSUNOMON, levelRange: { min: 3, max: 7 } },
      { seed: DigimonSeeds.KAPURIMON, levelRange: { min: 3, max: 7 } },
      { seed: DigimonSeeds.POYOMON, levelRange: { min: 1, max: 5 } },
      { seed: DigimonSeeds.TOKOMON, levelRange: { min: 2, max: 6 } },
      { seed: DigimonSeeds.PAGUMON, levelRange: { min: 2, max: 6 } },
    ],
    levelRange: { min: 1, max: 10 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_PIXEL_DESERT',
    img: 'assets/environments/pixeldesert.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.KOROMON, levelRange: { min: 5, max: 8 } },
      { seed: DigimonSeeds.AGUMON, levelRange: { min: 5, max: 10 } },
      { seed: DigimonSeeds.GEO_GREYMON, levelRange: { min: 8, max: 12 } },
      { seed: DigimonSeeds.APEMON, levelRange: { min: 8, max: 12 } },
      { seed: DigimonSeeds.SKULL_GREYMON, levelRange: { min: 10, max: 15 } },
      { seed: DigimonSeeds.METAL_GREYMON, levelRange: { min: 10, max: 15 } },
      { seed: DigimonSeeds.GROWLMON, levelRange: { min: 8, max: 12 } },
      { seed: DigimonSeeds.KUNEMON, levelRange: { min: 5, max: 10 } },
      { seed: DigimonSeeds.GABUMON, levelRange: { min: 5, max: 10 } },
      { seed: DigimonSeeds.GUILMON, levelRange: { min: 5, max: 10 } },
      { seed: DigimonSeeds.SUNMON, levelRange: { min: 5, max: 8 } },
      { seed: DigimonSeeds.CORONAMON, levelRange: { min: 6, max: 10 } },
      { seed: DigimonSeeds.BLACKAGUMON, levelRange: { min: 6, max: 11 } },
      { seed: DigimonSeeds.SHAMAMON, levelRange: { min: 7, max: 12 } },
      { seed: DigimonSeeds.FIRAMON, levelRange: { min: 9, max: 14 } },
      { seed: DigimonSeeds.TYRANNOMON, levelRange: { min: 10, max: 15 } },
    ],
    levelRange: { min: 5, max: 15 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_LABEL_FOREST',
    img: 'assets/environments/labelforest.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.TENTOMON, levelRange: { min: 10, max: 15 } },
      { seed: DigimonSeeds.KABUTERIMON, levelRange: { min: 12, max: 18 } },
      { seed: DigimonSeeds.MEGA_KABUTERIMON_RED, levelRange: { min: 15, max: 20 } },
      { seed: DigimonSeeds.MEGA_KABUTERIMON_BLUE, levelRange: { min: 15, max: 20 } },
      { seed: DigimonSeeds.KUNEMON, levelRange: { min: 10, max: 15 } },
      { seed: DigimonSeeds.MINOMON, levelRange: { min: 10, max: 14 } },
      { seed: DigimonSeeds.GATOMON, levelRange: { min: 12, max: 18 } },
      { seed: DigimonSeeds.SALAMON, levelRange: { min: 10, max: 15 } },
      { seed: DigimonSeeds.DOKUGUMON, levelRange: { min: 12, max: 18 } },
      { seed: DigimonSeeds.TANEMON, levelRange: { min: 10, max: 13 } },
      { seed: DigimonSeeds.PALMON, levelRange: { min: 11, max: 16 } },
      { seed: DigimonSeeds.TOGEMON, levelRange: { min: 14, max: 19 } },
      { seed: DigimonSeeds.BUDMON, levelRange: { min: 10, max: 13 } },
      { seed: DigimonSeeds.LALAMON, levelRange: { min: 11, max: 15 } },
      { seed: DigimonSeeds.SUNFLOWMON, levelRange: { min: 13, max: 18 } },
      { seed: DigimonSeeds.ARURAUMON, levelRange: { min: 12, max: 17 } },
      { seed: DigimonSeeds.WORMMON, levelRange: { min: 10, max: 15 } },
      { seed: DigimonSeeds.STINGMON, levelRange: { min: 13, max: 18 } },
      { seed: DigimonSeeds.DOKUNEMON, levelRange: { min: 11, max: 16 } },
      { seed: DigimonSeeds.KUWAGAMON, levelRange: { min: 14, max: 20 } },
    ],
    levelRange: { min: 10, max: 20 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_REGISTER_JUNGLE',
    img: 'assets/environments/registerjungle.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.GABUMON, levelRange: { min: 15, max: 20 } },
      { seed: DigimonSeeds.GARURUMON, levelRange: { min: 18, max: 22 } },
      { seed: DigimonSeeds.WAR_GARURUMON, levelRange: { min: 20, max: 25 } },
      { seed: DigimonSeeds.METAL_GARURUMON, levelRange: { min: 22, max: 25 } },
      { seed: DigimonSeeds.GOBURIMON, levelRange: { min: 15, max: 20 } },
      { seed: DigimonSeeds.DODOMON, levelRange: { min: 15, max: 18 } },
      { seed: DigimonSeeds.FUGAMON, levelRange: { min: 18, max: 22 } },
      { seed: DigimonSeeds.OGREMON, levelRange: { min: 18, max: 22 } },
      { seed: DigimonSeeds.ARMADILLOMON, levelRange: { min: 15, max: 20 } },
      { seed: DigimonSeeds.MONODRAMON, levelRange: { min: 16, max: 21 } },
      { seed: DigimonSeeds.KOTEMON, levelRange: { min: 15, max: 20 } },
      { seed: DigimonSeeds.DINOHUMON, levelRange: { min: 18, max: 23 } },
      { seed: DigimonSeeds.SHAMAMON, levelRange: { min: 17, max: 22 } },
      { seed: DigimonSeeds.KUMAMON, levelRange: { min: 16, max: 21 } },
      { seed: DigimonSeeds.GRIZZMON, levelRange: { min: 19, max: 24 } },
      { seed: DigimonSeeds.RENAMON, levelRange: { min: 16, max: 21 } },
      { seed: DigimonSeeds.KYUBIMON, levelRange: { min: 19, max: 24 } },
    ],
    levelRange: { min: 15, max: 25 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_PROXY_ISLAND',
    img: 'assets/environments/proxyisland.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.GOMAMON, levelRange: { min: 20, max: 25 } },
      { seed: DigimonSeeds.IKKAKUMON, levelRange: { min: 22, max: 28 } },
      { seed: DigimonSeeds.GIGIMON, levelRange: { min: 20, max: 24 } },
      { seed: DigimonSeeds.GUILMON, levelRange: { min: 20, max: 25 } },
      { seed: DigimonSeeds.GROWLMON, levelRange: { min: 22, max: 28 } },
      { seed: DigimonSeeds.WAR_GROWLMON, levelRange: { min: 25, max: 30 } },
      { seed: DigimonSeeds.GEO_GREYMON, levelRange: { min: 22, max: 28 } },
      { seed: DigimonSeeds.PUKAMON, levelRange: { min: 20, max: 23 } },
      { seed: DigimonSeeds.BETAMON, levelRange: { min: 20, max: 25 } },
      { seed: DigimonSeeds.SEADRAMON, levelRange: { min: 23, max: 28 } },
      { seed: DigimonSeeds.SYAKOMON, levelRange: { min: 21, max: 26 } },
      { seed: DigimonSeeds.SHELLMON, levelRange: { min: 23, max: 28 } },
      { seed: DigimonSeeds.GIZAMON, levelRange: { min: 21, max: 26 } },
      { seed: DigimonSeeds.GESOMON, levelRange: { min: 24, max: 29 } },
      { seed: DigimonSeeds.CRABMON, levelRange: { min: 21, max: 26 } },
      { seed: DigimonSeeds.EBIDRAMON, levelRange: { min: 24, max: 29 } },
    ],
    levelRange: { min: 20, max: 30 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_LIMIT_VALLEY',
    img: 'assets/environments/limitvalley.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.AGUMON, levelRange: { min: 25, max: 30 } },
      { seed: DigimonSeeds.GREYMON, levelRange: { min: 27, max: 32 } },
      { seed: DigimonSeeds.GEO_GREYMON, levelRange: { min: 28, max: 33 } },
      { seed: DigimonSeeds.RIZE_GREYMON, levelRange: { min: 30, max: 35 } },
      { seed: DigimonSeeds.SHINE_GREYMON, levelRange: { min: 32, max: 35 } },
      { seed: DigimonSeeds.BLUE_GREYMON, levelRange: { min: 28, max: 33 } },
      { seed: DigimonSeeds.DOKUGUMON, levelRange: { min: 27, max: 32 } },
      { seed: DigimonSeeds.KABUTERIMON, levelRange: { min: 27, max: 32 } },
      { seed: DigimonSeeds.MEGA_KABUTERIMON_BLUE, levelRange: { min: 30, max: 35 } },
      { seed: DigimonSeeds.MEGA_KABUTERIMON_RED, levelRange: { min: 30, max: 35 } },
      { seed: DigimonSeeds.MONODRAMON, levelRange: { min: 25, max: 30 } },
      { seed: DigimonSeeds.DORUMON, levelRange: { min: 25, max: 30 } },
      { seed: DigimonSeeds.DORUGAMON, levelRange: { min: 28, max: 33 } },
      { seed: DigimonSeeds.DKTYRANNOMON, levelRange: { min: 29, max: 34 } },
      { seed: DigimonSeeds.REPTILEDRAMON, levelRange: { min: 28, max: 33 } },
      { seed: DigimonSeeds.TYRANNOMON, levelRange: { min: 28, max: 33 } },
      { seed: DigimonSeeds.MONOCHROMON, levelRange: { min: 28, max: 33 } },
      { seed: DigimonSeeds.TRICERAMON, levelRange: { min: 30, max: 35 } },
    ],
    levelRange: { min: 25, max: 35 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_LOOP_SWAMP',
    img: 'assets/environments/loopswamp.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.BETAMON, levelRange: { min: 30, max: 35 } },
      { seed: DigimonSeeds.SEADRAMON, levelRange: { min: 32, max: 38 } },
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 35, max: 40 } },
      { seed: DigimonSeeds.GOMAMON, levelRange: { min: 30, max: 35 } },
      { seed: DigimonSeeds.IKKAKUMON, levelRange: { min: 32, max: 38 } },
      { seed: DigimonSeeds.ZUDOMON, levelRange: { min: 34, max: 40 } },
      { seed: DigimonSeeds.KYUKIMON, levelRange: { min: 32, max: 38 } },
      { seed: DigimonSeeds.OTAMAMON, levelRange: { min: 30, max: 35 } },
      { seed: DigimonSeeds.GEKOMON, levelRange: { min: 32, max: 37 } },
      { seed: DigimonSeeds.SYAKOMON, levelRange: { min: 30, max: 35 } },
      { seed: DigimonSeeds.COELAMON, levelRange: { min: 32, max: 37 } },
      { seed: DigimonSeeds.SHELLMON, levelRange: { min: 32, max: 37 } },
      { seed: DigimonSeeds.GESOMON, levelRange: { min: 33, max: 38 } },
      { seed: DigimonSeeds.OCTOMON, levelRange: { min: 34, max: 39 } },
      { seed: DigimonSeeds.NUMEMON, levelRange: { min: 31, max: 36 } },
      { seed: DigimonSeeds.SUKAMON, levelRange: { min: 31, max: 36 } },
      { seed: DigimonSeeds.RAREMON, levelRange: { min: 32, max: 37 } },
    ],
    levelRange: { min: 30, max: 40 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_ACCESS_GLACIER',
    img: 'assets/environments/accessglacier.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.GABUMON, levelRange: { min: 35, max: 40 } },
      { seed: DigimonSeeds.GARURUMON, levelRange: { min: 37, max: 42 } },
      { seed: DigimonSeeds.WAR_GARURUMON, levelRange: { min: 39, max: 45 } },
      { seed: DigimonSeeds.METAL_GARURUMON, levelRange: { min: 40, max: 45 } },
      { seed: DigimonSeeds.ZUDOMON, levelRange: { min: 38, max: 43 } },
      { seed: DigimonSeeds.VIKEMON, levelRange: { min: 40, max: 45 } },
      { seed: DigimonSeeds.SNOWAGUMON, levelRange: { min: 35, max: 40 } },
      { seed: DigimonSeeds.KUMAMON, levelRange: { min: 35, max: 40 } },
      { seed: DigimonSeeds.GRIZZMON, levelRange: { min: 37, max: 42 } },
      { seed: DigimonSeeds.PENGUINMON, levelRange: { min: 35, max: 40 } },
      { seed: DigimonSeeds.DOLPHMON, levelRange: { min: 37, max: 42 } },
      { seed: DigimonSeeds.FRIGIMON, levelRange: { min: 36, max: 41 } },
      { seed: DigimonSeeds.ICEMON, levelRange: { min: 36, max: 41 } },
      { seed: DigimonSeeds.HYOGAMON, levelRange: { min: 37, max: 42 } },
      { seed: DigimonSeeds.MOJYAMON, levelRange: { min: 37, max: 42 } },
    ],
    levelRange: { min: 35, max: 45 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_ANGLER_TUNNEL',
    img: 'assets/environments/anglertunnel.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.KOKUWAMON, levelRange: { min: 40, max: 45 } },
      { seed: DigimonSeeds.BLUE_METAL_GREYMON, levelRange: { min: 42, max: 48 } },
      { seed: DigimonSeeds.SHINE_GREYMON, levelRange: { min: 45, max: 50 } },
      { seed: DigimonSeeds.SKULL_GREYMON, levelRange: { min: 43, max: 48 } },
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 45, max: 50 } },
      { seed: DigimonSeeds.HAGURUMON, levelRange: { min: 40, max: 45 } },
      { seed: DigimonSeeds.GUARDROMON, levelRange: { min: 42, max: 47 } },
      { seed: DigimonSeeds.ANDROMON, levelRange: { min: 44, max: 49 } },
      { seed: DigimonSeeds.MEKANORIMON, levelRange: { min: 41, max: 46 } },
      { seed: DigimonSeeds.TANKMON, levelRange: { min: 43, max: 48 } },
      { seed: DigimonSeeds.GOTSUMON, levelRange: { min: 40, max: 45 } },
      { seed: DigimonSeeds.ICEMON, levelRange: { min: 41, max: 46 } },
      { seed: DigimonSeeds.SOLARMON, levelRange: { min: 40, max: 45 } },
      { seed: DigimonSeeds.STARMON, levelRange: { min: 42, max: 47 } },
    ],
    levelRange: { min: 40, max: 50 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_MAGNET_MINE',
    img: 'assets/environments/magnetmine.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.RIZE_GREYMON, levelRange: { min: 45, max: 50 } },
      { seed: DigimonSeeds.METAL_GREYMON, levelRange: { min: 46, max: 52 } },
      { seed: DigimonSeeds.WAR_GREYMON, levelRange: { min: 48, max: 55 } },
      { seed: DigimonSeeds.SKULL_GREYMON, levelRange: { min: 47, max: 53 } },
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.KOKUWAMON, levelRange: { min: 45, max: 50 } },
      { seed: DigimonSeeds.GUARDROMON, levelRange: { min: 47, max: 52 } },
      { seed: DigimonSeeds.ANDROMON, levelRange: { min: 49, max: 54 } },
      { seed: DigimonSeeds.MEKANORIMON, levelRange: { min: 46, max: 51 } },
      { seed: DigimonSeeds.TANKMON, levelRange: { min: 48, max: 53 } },
      { seed: DigimonSeeds.GOTSUMON, levelRange: { min: 45, max: 50 } },
      { seed: DigimonSeeds.ICEMON, levelRange: { min: 46, max: 51 } },
      { seed: DigimonSeeds.SOLARMON, levelRange: { min: 45, max: 50 } },
      { seed: DigimonSeeds.STARMON, levelRange: { min: 47, max: 52 } },
      { seed: DigimonSeeds.HIANDROMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.METALMAMEMON, levelRange: { min: 48, max: 53 } },
    ],
    levelRange: { min: 45, max: 55 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_PACKET_COAST',
    img: 'assets/environments/packetcoast.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.TSUNOMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.ARMADILLOMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.GOMAMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.IKKAKUMON, levelRange: { min: 52, max: 58 } },
      { seed: DigimonSeeds.GREYMON, levelRange: { min: 52, max: 58 } },
      { seed: DigimonSeeds.GEO_GREYMON, levelRange: { min: 53, max: 58 } },
      { seed: DigimonSeeds.RIZE_GREYMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.SHINE_GREYMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.BETAMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.SEADRAMON, levelRange: { min: 52, max: 57 } },
      { seed: DigimonSeeds.MEGASEADRAMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.SYAKOMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.SHELLMON, levelRange: { min: 52, max: 57 } },
      { seed: DigimonSeeds.PENGUINMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.DOLPHMON, levelRange: { min: 52, max: 57 } },
      { seed: DigimonSeeds.GIZAMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.GESOMON, levelRange: { min: 52, max: 57 } },
      { seed: DigimonSeeds.CRABMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.EBIDRAMON, levelRange: { min: 52, max: 57 } },
      { seed: DigimonSeeds.KAMEMON, levelRange: { min: 50, max: 55 } },
      { seed: DigimonSeeds.GAWAPPAMON, levelRange: { min: 52, max: 57 } },
    ],
    levelRange: { min: 50, max: 60 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_PALLETE_AMAZON',
    img: 'assets/environments/paletteamazon.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.BETAMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.OGREMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.IKKAKUMON, levelRange: { min: 57, max: 62 } },
      { seed: DigimonSeeds.KABUTERIMON, levelRange: { min: 57, max: 62 } },
      { seed: DigimonSeeds.MEGA_KABUTERIMON_BLUE, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.MEGA_KABUTERIMON_RED, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.HERCULES_KABUTERIMON, levelRange: { min: 62, max: 65 } },
      { seed: DigimonSeeds.PALMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.TOGEMON, levelRange: { min: 57, max: 62 } },
      { seed: DigimonSeeds.LILLYMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.FLORAMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.VEGGIEMON, levelRange: { min: 57, max: 62 } },
      { seed: DigimonSeeds.WOODMON, levelRange: { min: 57, max: 62 } },
      { seed: DigimonSeeds.REDVEGIEMON, levelRange: { min: 57, max: 62 } },
      { seed: DigimonSeeds.BLOSSOMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.CHERRYMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.ARURAUMON, levelRange: { min: 55, max: 60 } },
      { seed: DigimonSeeds.WEEDMON, levelRange: { min: 57, max: 62 } },
    ],
    levelRange: { min: 55, max: 65 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_THRILLER_RUINS',
    img: 'assets/environments/thrillerruins.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 60, max: 68 } },
      { seed: DigimonSeeds.KUZUHAMON, levelRange: { min: 62, max: 70 } },
      { seed: DigimonSeeds.BLACK_WAR_GREYMON, levelRange: { min: 62, max: 70 } },
      { seed: DigimonSeeds.MEGIDRAMON, levelRange: { min: 62, max: 70 } },
      { seed: DigimonSeeds.DOKUGUMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.KOKUWAMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.DEMIDEVIMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.DEVIMON, levelRange: { min: 62, max: 67 } },
      { seed: DigimonSeeds.BAKEMON, levelRange: { min: 61, max: 66 } },
      { seed: DigimonSeeds.PHANTOMON, levelRange: { min: 63, max: 68 } },
      { seed: DigimonSeeds.MYOTISMON, levelRange: { min: 64, max: 69 } },
      { seed: DigimonSeeds.TSUKAIMON, levelRange: { min: 60, max: 65 } },
      { seed: DigimonSeeds.ICEDEVIMON, levelRange: { min: 62, max: 67 } },
      { seed: DigimonSeeds.VILEMON, levelRange: { min: 61, max: 66 } },
      { seed: DigimonSeeds.LADYDEVIMON, levelRange: { min: 64, max: 70 } },
      { seed: DigimonSeeds.PIEDMON, levelRange: { min: 65, max: 70 } },
    ],
    levelRange: { min: 60, max: 70 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_RISK_FACTORY',
    img: 'assets/environments/riskfactory.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.AIRDRAMON, levelRange: { min: 65, max: 70 } },
      { seed: DigimonSeeds.METAL_GREYMON, levelRange: { min: 65, max: 72 } },
      { seed: DigimonSeeds.BLUE_METAL_GREYMON, levelRange: { min: 67, max: 73 } },
      { seed: DigimonSeeds.WAR_GREYMON, levelRange: { min: 68, max: 75 } },
      { seed: DigimonSeeds.SKULL_GREYMON, levelRange: { min: 67, max: 73 } },
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 70, max: 75 } },
      { seed: DigimonSeeds.DOKUGUMON, levelRange: { min: 65, max: 70 } },
      { seed: DigimonSeeds.KOKUWAMON, levelRange: { min: 65, max: 70 } },
      { seed: DigimonSeeds.HAGURUMON, levelRange: { min: 65, max: 70 } },
      { seed: DigimonSeeds.GUARDROMON, levelRange: { min: 67, max: 72 } },
      { seed: DigimonSeeds.ANDROMON, levelRange: { min: 69, max: 74 } },
      { seed: DigimonSeeds.MEKANORIMON, levelRange: { min: 66, max: 71 } },
      { seed: DigimonSeeds.TANKMON, levelRange: { min: 68, max: 73 } },
      { seed: DigimonSeeds.CLOCKMON, levelRange: { min: 67, max: 72 } },
      { seed: DigimonSeeds.GIROMON, levelRange: { min: 69, max: 74 } },
      { seed: DigimonSeeds.METALMAMEMON, levelRange: { min: 68, max: 73 } },
      { seed: DigimonSeeds.HIANDROMON, levelRange: { min: 70, max: 75 } },
    ],
    levelRange: { min: 65, max: 75 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_SHADOW_ABYSS',
    img: 'assets/environments/shadowabyss.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.BETAMON, levelRange: { min: 70, max: 75 } },
      { seed: DigimonSeeds.SEADRAMON, levelRange: { min: 72, max: 78 } },
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 75, max: 85 } },
      { seed: DigimonSeeds.MEGIDRAMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.AIRDRAMON, levelRange: { min: 70, max: 75 } },
      { seed: DigimonSeeds.GUILMON, levelRange: { min: 70, max: 75 } },
      { seed: DigimonSeeds.GROWLMON, levelRange: { min: 72, max: 78 } },
      { seed: DigimonSeeds.WAR_GROWLMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.GEO_GREYMON, levelRange: { min: 72, max: 78 } },
      { seed: DigimonSeeds.ZEKE_GREYMON, levelRange: { min: 75, max: 85 } },
      { seed: DigimonSeeds.KERAMON, levelRange: { min: 70, max: 75 } },
      { seed: DigimonSeeds.KURISARIMON, levelRange: { min: 72, max: 77 } },
      { seed: DigimonSeeds.INFERMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.DEMIDEVIMON, levelRange: { min: 70, max: 75 } },
      { seed: DigimonSeeds.DEVIMON, levelRange: { min: 72, max: 77 } },
      { seed: DigimonSeeds.MYOTISMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.DRACMON, levelRange: { min: 70, max: 75 } },
      { seed: DigimonSeeds.SANGLOUPMON, levelRange: { min: 72, max: 77 } },
      { seed: DigimonSeeds.MATADORMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.MARINE_DEVIMON, levelRange: { min: 75, max: 85 } },
      { seed: DigimonSeeds.DRAGOMON, levelRange: { min: 75, max: 85 } },
      { seed: DigimonSeeds.MEGASEADRAMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.METALSEADRAMON, levelRange: { min: 80, max: 85 } },
    ],
    levelRange: { min: 70, max: 85 },
  },
  {
    name: 'MODULES.ADVENTURE.EXPLORE_SECTION.LOCATION_WIZARD_TEMPLE',
    img: 'assets/environments/wizardtemple.png',
    possibleEcounterDigimonSeeds: [
      { seed: DigimonSeeds.ANGEWOMON, levelRange: { min: 75, max: 85 } },
      { seed: DigimonSeeds.OPHANIMON, levelRange: { min: 80, max: 90 } },
      { seed: DigimonSeeds.HOLYDRAMON, levelRange: { min: 85, max: 95 } },
      { seed: DigimonSeeds.KYUKIMON, levelRange: { min: 75, max: 85 } },
      { seed: DigimonSeeds.KUZUHAMON, levelRange: { min: 80, max: 90 } },
      { seed: DigimonSeeds.DOKUGUMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.MEGIDRAMON, levelRange: { min: 80, max: 90 } },
      { seed: DigimonSeeds.MACHINEDRAMON, levelRange: { min: 85, max: 95 } },
      { seed: DigimonSeeds.BLACK_WAR_GREYMON, levelRange: { min: 85, max: 95 } },
      { seed: DigimonSeeds.SKULL_GREYMON, levelRange: { min: 80, max: 90 } },
      { seed: DigimonSeeds.TAPIRMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.SEASARMON, levelRange: { min: 77, max: 82 } },
      { seed: DigimonSeeds.UNIMON, levelRange: { min: 76, max: 81 } },
      { seed: DigimonSeeds.ANGEMON, levelRange: { min: 77, max: 82 } },
      { seed: DigimonSeeds.MAGNAANGEMON, levelRange: { min: 80, max: 85 } },
      { seed: DigimonSeeds.KUDAMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.REPPAMON, levelRange: { min: 77, max: 82 } },
      { seed: DigimonSeeds.TYILINMON, levelRange: { min: 80, max: 85 } },
      { seed: DigimonSeeds.WIZARDMON, levelRange: { min: 77, max: 82 } },
      { seed: DigimonSeeds.PHANTOMON, levelRange: { min: 80, max: 85 } },
      { seed: DigimonSeeds.MYOTISMON, levelRange: { min: 82, max: 87 } },
      { seed: DigimonSeeds.DEVIMON, levelRange: { min: 77, max: 82 } },
      { seed: DigimonSeeds.LADYDEVIMON, levelRange: { min: 80, max: 85 } },
      { seed: DigimonSeeds.GATOMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.ANGEWOMON, levelRange: { min: 78, max: 83 } },
      { seed: DigimonSeeds.SALAMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.PATAMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.ANGEMON, levelRange: { min: 78, max: 83 } },
      { seed: DigimonSeeds.MAGNAANGEMON, levelRange: { min: 81, max: 86 } },
      { seed: DigimonSeeds.KUDAMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.REPPAMON, levelRange: { min: 78, max: 83 } },
      { seed: DigimonSeeds.TYILINMON, levelRange: { min: 81, max: 86 } },
      { seed: DigimonSeeds.RENAMON, levelRange: { min: 75, max: 80 } },
      { seed: DigimonSeeds.KYUBIMON, levelRange: { min: 78, max: 83 } },
      { seed: DigimonSeeds.TAOMON, levelRange: { min: 81, max: 86 } },
    ],
    levelRange: { min: 75, max: 95 },
  },
];
